name: epicurrence
favicon: null
layout_spectrum: 0.41086
typography_spectrum: 0.07172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#1b1717'
    - '#767982'
    - '#df4b31'
    - '#b3a5a5'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
