name: epicurrence
favicon: null
layout_spectrum: 0.31351
typography_spectrum: 0.96107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#261815'
    - '#dcf0cb'
    - '#d84d46'
    - '#947f7b'
    - '#c9b9b9'
  brandStrength: 0
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 1
purpose: []
