name: epicurrence
favicon: null
layout_spectrum: 0.41086
typography_spectrum: 0.07172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff623f'
    - '#e9e3e3'
    - '#1c1817'
    - '#00a7cb'
    - '#accd00'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
