name: epicurrence
favicon: null
layout_spectrum: 0.3709
typography_spectrum: 0.7459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#1b1717'
    - '#767982'
    - '#df4b31'
    - '#b3a5a5'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 1
purpose: []
