typography_spectrum: 1
color:
  brandColors:
    - '#261815'
    - '#dcf0cb'
    - '#d84d46'
    - '#947f7b'
    - '#c9b9b9'
  brandStrength: 0
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.32274
analytics:
  google: null
  facebook: null
  twitter: null
name: epicurrence
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
favicon: null
purpose: []
